//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Merit.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Merideum.Merit.Antlr {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="MeritParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface IMeritListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeritParser.parse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParse([NotNull] MeritParser.ParseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeritParser.parse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParse([NotNull] MeritParser.ParseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeritParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] MeritParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeritParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] MeritParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeritParser.importDependency"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportDependency([NotNull] MeritParser.ImportDependencyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeritParser.importDependency"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportDependency([NotNull] MeritParser.ImportDependencyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeritParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] MeritParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeritParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] MeritParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeritParser.outputAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOutputAssignment([NotNull] MeritParser.OutputAssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeritParser.outputAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOutputAssignment([NotNull] MeritParser.OutputAssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeritParser.variableAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableAssignment([NotNull] MeritParser.VariableAssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeritParser.variableAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableAssignment([NotNull] MeritParser.VariableAssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeritParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] MeritParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeritParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] MeritParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>integerExpression</c>
	/// labeled alternative in <see cref="MeritParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntegerExpression([NotNull] MeritParser.IntegerExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>integerExpression</c>
	/// labeled alternative in <see cref="MeritParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntegerExpression([NotNull] MeritParser.IntegerExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeritParser.variableModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableModifier([NotNull] MeritParser.VariableModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeritParser.variableModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableModifier([NotNull] MeritParser.VariableModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeritParser.dependencyPathIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDependencyPathIdentifier([NotNull] MeritParser.DependencyPathIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeritParser.dependencyPathIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDependencyPathIdentifier([NotNull] MeritParser.DependencyPathIdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeritParser.simpleIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleIdentifier([NotNull] MeritParser.SimpleIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeritParser.simpleIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleIdentifier([NotNull] MeritParser.SimpleIdentifierContext context);
}
} // namespace Merideum.Merit.Antlr
